[env:seeed_xiao_esp32s3]
platform = espressif32
board = seeed_xiao_esp32s3
framework = arduino
monitor_speed = 115200
board_build.partitions = huge_app.csv
build_flags =
    -DBOARD_HAS_PSRAM
    -DCAMERA_MODEL_XIAO_ESP32S3
    -DCORE_DEBUG_LEVEL=3
